# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urllist',
            old_name='priority_posting',
            new_name='posting_priority',
        ),
        migrations.AddField(
            model_name='urllist',
            name='posting_url',
            field=models.URLField(default=''),
        ),
    ]
