# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobList', '0002_auto_20160813_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='text',
            field=models.TextField(default=datetime.datetime(2016, 8, 16, 21, 42, 9, 403044, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
