# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobList', '0003_urllist_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllist',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
